### ISSUE TITLE
msbuild properties to choose which attribute to write

### ISSUE THREAD

**Issue by cortex93** [Zoltu/Zoltu.Versioning#14]
Sometimes, we need to keep control over AssemblyVersion attribute and let others be generated.
Adding some msbuild properties to control which attribute is written out would allow this scenario and others combinations.

Like
```
<PropertyGroup>
   <GitAssemblyVersion>false</GitAssemblyVersion>
   <GitAssemblyFileVersion>false</GitAssemblyFileVersion>
   <GitAssemblyInformational>false</GitAssemblyInformationalVersion>
</PropertyGroup>
```

**Comment by Zoltu** [comment]
@cortex93 Can you help me understand the scenario you are in in which you want to use automatic versioning but you don't want your assemblies to be versioned with it?

**Comment by Zoltu** [comment]
What value do you get from Zoltu.Versioning when used in the way you have requested here?

**Comment by cortex93** [comment]
I want to version but only the file version and product version. Not the assembly one. For eg. SharePoint development makes it not easy to handle assembly binding redirect. And thus, you need to control the assembly file version. For example, all SharePoint 2013 assembly have a 15.0.0.0 assembly version but can have a file version like 15.0.4699.1000 depending on the patches/hotfix you applied.

Moreover, we get closer to what the assembly version task does with TFVC.

I can make a pull request, if you want.

**Comment by Zoltu** [comment]
Fixed in https://github.com/Zoltu/Zoltu.Versioning/commit/5c7e676bd11160a4f4b04e86e3d9726a9cf01e45.

These are the properties you will want to set via MSBuild:
```
<GitVersionIncludeAssemblyVersion>true</GitVersionIncludeAssemblyVersion>
<GitVersionIncludeAssemblyFileVersion>true</GitVersionIncludeAssemblyFileVersion>
<GitVersionIncludeAssemblyInformationalVersion>true</GitVersionIncludeAssemblyInformationalVersion>
```

**Comment by Zoltu** [comment]
Available on NuGet: https://www.nuget.org/packages/Zoltu.Versioning/1.2.23

**Comment by cortex93** [comment]
Thank you, works as requested
